name: autofix.ci
on: { push: {}, pull_request: {} }
permissions: { contents: read }
jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: npm i -fg corepack && corepack enable
      - uses: actions/setup-node@v6
        with: { node-version: lts/*, cache: pnpm }
      - run: pnpm install
      - run: pnpm lint:fix
      - uses: autofix-ci/action@ff86a557419858bb967097bfc916833f5647fa8c